# Logstash %%LOGSTASH_VERSION%%

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM %%UPSTREAM_IMAGE_DIGEST%%

# The upstream image was built by:
#   %%UPSTREAM_DOCKERFILE_LINK%%

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
