# Logstash 7.0.0

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:7.0.0@sha256:4d6c69575f150ac962bb2950bef24b6e3c677bfa325b0fa36c8c6493f143fd86

# The upstream image was built by:
#   https://github.com/elastic/logstash-docker/tree/7.0.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
