# Logstash 7.6.1

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:7.6.1@sha256:462ff0cfd3a3ec444e0dccb11dd1ac0a3f52502616b3efaf4ae1aee90f9b7e13

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v7.6.1/logstash

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
