# Logstash 6.4.3

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:6.4.3@sha256:392a232fdde65fb4821fc0d5e00ded19fec721226e1550bff4ab8ca84447d719

# The upstream image was built by:
#   https://github.com/elastic/logstash-docker/tree/6.4.3

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
