# Logstash 6.5.1

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:6.5.1@sha256:11ae4d096e177f70c5dca1f4640ea86eb10cebf1a45a00032de42ed7144bdf4c

# The upstream image was built by:
#   https://github.com/elastic/logstash-docker/tree/6.5.1

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
