# Logstash 6.4.0

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:6.4.0@sha256:40bbb687fc820c892906fd325ad9ffacb96a56ab252a919fd2a60f315b374af1

# The upstream image was built by:
#   https://github.com/elastic/logstash-docker/tree/6.4.0

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
