# Logstash 6.4.1

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/logstash/logstash:6.4.1@sha256:e9c84f1a0e39ee74b7f8d14a6fa4024e836b8ce1594c03744af365a16066c624

# The upstream image was built by:
#   https://github.com/elastic/logstash-docker/tree/6.4.1

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Logstash documentation visit https://www.elastic.co/guide/en/logstash/current/docker.html

# See https://github.com/docker-library/official-images/pull/5039 for more details.
